server:
  port: 9100
  servlet:
    context-path: /pvs-api

message:
  exception: "exception error"
  success: "你成功了!"
  fail: "你失敗了!"
  invalid:
    url: "你連URL都不會打嗎?"

webClient:
  baseUrl:
    sonar: "http://localhost:9000/api"
    github: "https://api.github.com/graphql"
    test: ""
#
#logging:
#  config: classpath:log4j2.xml

spring:
  profiles:
    active: test
  datasource:
    url: jdbc:postgresql://localhost:5432/PVS
    username: "Your db username"
    password: "Your db user password"
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  jackson:
    time-zone: Asia/Taipei
  security:
    oauth2:
      client:
        registration:
          gitlab:
            client-id: "Your client key"
            client-secret: "Your client secret key"
            authorization-grant-type: authorization_code
            redirectUriTemplate: '{baseUrl}/login/oauth2/code/{registrationId}'
            scope:
              - read_user
              - read_api
              - read_repository
            clientName: GitLab
        provider:
          gitlab:
            authorization-uri: https://gitlab.com/oauth/authorize
            token-uri: https://gitlab.com/oauth/token
            user-info-uri: https://gitlab.com/api/v4/user
            jwk-set-uri: https://gitlab.com/oauth/discovery/keys
            user-name-attribute: username

frontend:
  redirect-url: http://localhost:3001/select